"""
Learning Log Model
Market AI V2
"""

# {
#   "strategy_name": "EMA_MACD_V1",
#   "strategy_version": 2,
#   "symbol": "BTCUSDT",
#   "timeframe": "5m",
#   "trade_id": "TRD_10025",
#   "result": "LOSS",
#   "pnl": -245.25,
#   "confidence": 82,
#   "score": 4,
#   "market_regime": "RANGING",
#   "learning_action": "Decrease BUY threshold",
#   "parameter_changed": "buy_threshold",
#   "previous_value": 3,
#   "new_value": 4,
#   "improvement_reason": "High number of false BUY signals in ranging markets",
#   "indicators": {
#     "rsi": 68.2,
#     "adx": 19.4,
#     "ema20": 106450,
#     "ema50": 106320
#   },
#   "created_at": "2026-07-02T10:30:45Z",
#   "notes": "Automatically generated by Learning Engine"
# }

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


@dataclass
class LearningLog:

    strategy_name: str

    strategy_version: int

    symbol: str

    timeframe: str

    trade_id: str

    result: str

    pnl: float

    confidence: float

    score: int

    market_regime: str

    learning_action: str

    parameter_changed: str = ""

    previous_value: Optional[float] = None

    new_value: Optional[float] = None

    improvement_reason: str = ""

    indicators: dict = field(default_factory=dict)

    created_at: datetime = field(default_factory=datetime.utcnow)

    notes: str = ""

    def to_dict(self):

        return {
            "strategy_name": self.strategy_name,
            "strategy_version": self.strategy_version,
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "trade_id": self.trade_id,
            "result": self.result,
            "pnl": self.pnl,
            "confidence": self.confidence,
            "score": self.score,
            "market_regime": self.market_regime,
            "learning_action": self.learning_action,
            "parameter_changed": self.parameter_changed,
            "previous_value": self.previous_value,
            "new_value": self.new_value,
            "improvement_reason": self.improvement_reason,
            "indicators": self.indicators,
            "created_at": self.created_at,
            "notes": self.notes,
        }

    @classmethod
    def from_dict(cls, data):

        return cls(
            strategy_name=data.get("strategy_name", ""),
            strategy_version=data.get("strategy_version", 1),
            symbol=data.get("symbol", ""),
            timeframe=data.get("timeframe", ""),
            trade_id=data.get("trade_id", ""),
            result=data.get("result", ""),
            pnl=data.get("pnl", 0.0),
            confidence=data.get("confidence", 0.0),
            score=data.get("score", 0),
            market_regime=data.get("market_regime", ""),
            learning_action=data.get("learning_action", ""),
            parameter_changed=data.get("parameter_changed", ""),
            previous_value=data.get("previous_value"),
            new_value=data.get("new_value"),
            improvement_reason=data.get("improvement_reason", ""),
            indicators=data.get("indicators", {}),
            created_at=data.get("created_at", datetime.utcnow()),
            notes=data.get("notes", ""),
        )
